
-- create
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
   address TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Clark', 18, 'Moscow');
INSERT INTO EMPLOYEE VALUES (0002, 'Dave', 18, 'Nevada');
INSERT INTO EMPLOYEE VALUES (0003, 'Alex', 16, 'Rome' );
INSERT INTO EMPLOYEE VALUES (0004, 'Shot', 15, 'Berlin');
INSERT INTO EMPLOYEE VALUES (0005, 'Sasha', 17, 'Cherven');
INSERT INTO EMPLOYEE VALUES (0006, 'Ava', 16, 'Mogilev');

-- fetch 
SELECT * FROM EMPLOYEE WHERE age = 18;
